services:
- docker
sudo: false
script:
  ./project.rb
deploy:
  - provider: script
    script: ./project.rb clojars-deploy-via-travis
    on:
      tags: true
  - provider: script
    script: ./project.rb clojars-deploy-via-travis snapshot
    on:
      branch: master
env:
  global:
    secure: lk2zcu23sRyJ4fqoKEpmP4dDHnaWp6Jpx28TWHz9n5GlGm+THmTjgI76d2/vvkDXKFbV4JQua3EOTTI4AhpgBPIDBEWN5BYa/Tz+EpKI2zkAYrpVMslxF33kENMj6i875QfjUrSLtxzupaEKWbHRxsWII/cpw2NbCoRAIQXa/W27BccSXGH72ysJJZNLJzL0X1c6saDCMEqNQ8oLPVe9KQ6mVWWtTtaW94c0b7eVHPMnsdUBqZWLe6hYs5/R2UsmCh+KmBamfib20kvk6ohXcrTusMasBOsWmWBLYReIVW+Uy5ZHO6AUOJfZwmnjSv1uthtRLcWcAiq5fx9ozTIDfVrYKLamW3wEVDNYVZBXp3fJHaDJTsSL7ePKv4I3lb7gi+ne83P9kTXergh974mRko4tVxM4fss9nYMYodqoPEKgIM66+zVLzMB4+dXymX1zR6VfhJWqnnTqnuWCVAhvgB/FYMsXqtBmq3cd5H1quoW8sPo+9iuBeSBfUCyrmKNlPqzPEeaEjkKRfwDI7FWlGPsUEGvINoFhIqbMP8Od9NBoH8QPtXXJ/H+GGMXPC/8LLnvVw53qKgdWh+Pqv0iJPrT5zwuzksjLoMDvY719BCIiX+KB2Zg82rba04dOh4RCGzPd129KYQxief+d0QQ1lJl1S+l6IOMBDiok6OG6gZ4=
